// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OurProduct.Models;

namespace OurProduct.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20200402113103_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OurProduct.Models.Product", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PDesc");

                    b.Property<string>("PName");

                    b.Property<int>("PPrice");

                    b.HasKey("PId");

                    b.ToTable("Product");

                    b.HasData(
                        new { PId = 1, PDesc = "Stationery", PName = "Pen", PPrice = 10 },
                        new { PId = 2, PDesc = "Gadget", PName = "Mobile", PPrice = 500 },
                        new { PId = 3, PDesc = "Gadget", PName = "Watch", PPrice = 500 },
                        new { PId = 4, PDesc = "Stationery", PName = "NoteBook", PPrice = 50 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
